[package]
name = "jolt-store"
version.workspace = true
edition.workspace = true

[dependencies]
jolt-core = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
jolt-identity = { workspace = true }
tempfile = { workspace = true }
